# Generated by Django 3.0.2 on 2020-01-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
