# Generated by Django 3.0.2 on 2020-01-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0002_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(default='Not Listed', max_length=255),
        ),
    ]
